services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@db:5432/spina_app
    restart: unless-stopped
    command: ["/bin/sh", "-c", "bundle install && rails generate spina:install && rails db:migrate && rails s -b 0.0.0.0"]

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

volumes:
  postgres_data: